# Generated by Django 4.2 on 2024-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedfood',
            new_name='processed_food_barcode_index',
            old_name='barcode_index',
        ),
        migrations.AddIndex(
            model_name='cookedfood',
            index=models.Index(fields=['food_code'], name='cooked_food_code_index'),
        ),
        migrations.AddIndex(
            model_name='cookedfood',
            index=models.Index(fields=['food_name'], name='cooked_food_name_index'),
        ),
        migrations.AddIndex(
            model_name='cookedfood',
            index=models.Index(fields=['category_main', 'category_sub'], name='cooked_food_category_index'),
        ),
        migrations.AddIndex(
            model_name='customizedfood',
            index=models.Index(fields=['food_code'], name='customized_food_code_index'),
        ),
        migrations.AddIndex(
            model_name='customizedfood',
            index=models.Index(fields=['food_name'], name='customized_food_name_index'),
        ),
        migrations.AddIndex(
            model_name='customizedfood',
            index=models.Index(fields=['category_main', 'category_sub'], name='customized_food_category_index'),
        ),
        migrations.AddIndex(
            model_name='freshfood',
            index=models.Index(fields=['food_code'], name='fresh_food_code_index'),
        ),
        migrations.AddIndex(
            model_name='freshfood',
            index=models.Index(fields=['food_name'], name='fresh_food_name_index'),
        ),
        migrations.AddIndex(
            model_name='freshfood',
            index=models.Index(fields=['category_main', 'category_sub'], name='fresh_food_category_index'),
        ),
        migrations.AddIndex(
            model_name='processedfood',
            index=models.Index(fields=['food_code'], name='processed_food_code_index'),
        ),
        migrations.AddIndex(
            model_name='processedfood',
            index=models.Index(fields=['food_name'], name='processed_food_name_index'),
        ),
        migrations.AddIndex(
            model_name='processedfood',
            index=models.Index(fields=['category_main', 'category_sub'], name='processed_food_category_index'),
        ),
        migrations.AlterModelTable(
            name='cookedfood',
            table='cooked_food',
        ),
        migrations.AlterModelTable(
            name='cookednutrition',
            table='cooked_nutrition',
        ),
        migrations.AlterModelTable(
            name='customizedfood',
            table='customized_food',
        ),
        migrations.AlterModelTable(
            name='customizedmetadata',
            table='customized_metadata',
        ),
        migrations.AlterModelTable(
            name='customizednutrition',
            table='customized_nutrition',
        ),
        migrations.AlterModelTable(
            name='freshfood',
            table='fresh_food',
        ),
        migrations.AlterModelTable(
            name='freshnutrition',
            table='fresh_nutrition',
        ),
        migrations.AlterModelTable(
            name='processedfood',
            table='processed_food',
        ),
        migrations.AlterModelTable(
            name='processednutrition',
            table='processed_nutrition',
        ),
    ]
