# Generated by Django 4.2 on 2024-03-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_cookedfood_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processednutrition',
            name='processed_food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition_info', serialize=False, to='food.processedfood', verbose_name='가공식품'),
        ),
    ]
