# Generated by Django 4.2 on 2024-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_cookednutrition_cooked_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedmetadata',
            name='food_type',
            field=models.CharField(choices=[('P', 'Processed Food'), ('F', 'Fresh Food'), ('C', 'Cooked Food')], max_length=50, verbose_name='식품 종류'),
        ),
    ]
