# Generated by Django 4.2 on 2024-04-09 04:39

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_customizedmetadata_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedfood',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to=food.models.food_image_path, verbose_name='식품 이미지'),
        ),
        migrations.AlterField(
            model_name='customizedfood',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to=food.models.food_image_path, verbose_name='식품 이미지'),
        ),
        migrations.AlterField(
            model_name='freshfood',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to=food.models.food_image_path, verbose_name='식품 이미지'),
        ),
        migrations.AlterField(
            model_name='processedfood',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to=food.models.food_image_path, verbose_name='식품 이미지'),
        ),
    ]
