services:
  django_app:
    container_name: diningcoach-server
    image: django_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    volumes:
      - ./diningcoach:/diningcoach
    working_dir: /diningcoach
    command: gunicorn --bind 0.0.0.0:8000 diningcoach.wsgi:application
    env_file:
      - ./diningcoach/.env
    depends_on:
      - redis

  celery_worker:
    container_name: celery-worker
    image: django_app
    volumes:
      - ./diningcoach:/diningcoach
    working_dir: /diningcoach
    command: celery -A diningcoach worker -l info
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - django_app
      - redis

  celery_beat:
    container_name: celery-beat
    image: django_app
    volumes:
      - ./diningcoach:/diningcoach
    working_dir: /diningcoach
    command: celery -A diningcoach beat -l info
    depends_on:
      - django_app
      - redis

  redis:
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx-server
    image: nginx:latest
    volumes:
      - ./diningcoach:/diningcoach
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django_app
