# Generated by Django 4.2 on 2024-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='회원 아이디')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='비밀번호')),
                ('nickname', models.CharField(default='회원', max_length=255, verbose_name='닉네임')),
                ('platform_type', models.CharField(blank=True, choices=[(0, 'DiningCoach'), (1, 'Kakao'), (2, 'Naver'), (3, 'Google'), (4, 'Apple')], max_length=50, null=True, verbose_name='가입 플랫폼 종류')),
                ('platform_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='가입 플랫폼 ID')),
                ('user_agent', models.TextField(verbose_name='가입 환경 정보')),
                ('is_inactive', models.BooleanField(default=False, verbose_name='휴면회원 여부')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', verbose_name='회원')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='리프레시 토큰')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '리프레시 토큰',
                'verbose_name_plural': '리프레시 토큰',
                'db_table': 'refresh_token',
            },
        ),
        migrations.CreateModel(
            name='UserBasic',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', verbose_name='회원')),
                ('consent_terms', models.BooleanField(default=False, verbose_name='필수약관 동의 여부')),
                ('receive_marketing', models.BooleanField(default=False, verbose_name='마케팅정보 수신 여부')),
                ('gender', models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], max_length=50, null=True, verbose_name='성별')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='자기소개')),
                ('profile_image', models.TextField(blank=True, null=True, verbose_name='프로필 사진')),
            ],
            options={
                'verbose_name': '회원 기본정보',
                'verbose_name_plural': '회원 기본정보',
                'db_table': 'user_basic',
            },
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user', verbose_name='회원')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='키')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='몸무게')),
                ('workout_time', models.IntegerField(blank=True, null=True, verbose_name='평균 운동량')),
                ('sleep_time', models.IntegerField(blank=True, null=True, verbose_name='평균 수면시간')),
                ('allergy_info', models.TextField(blank=True, null=True, verbose_name='알레르기 정보')),
                ('habit_info', models.TextField(blank=True, null=True, verbose_name='특이 식습관 정보')),
                ('preference_info', models.TextField(blank=True, null=True, verbose_name='선호 음식 정보')),
            ],
            options={
                'verbose_name': '회원 추가정보',
                'verbose_name_plural': '회원 추가정보',
                'db_table': 'user_extra',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_id_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='user_nickname_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_index'),
        ),
    ]
