# Generated by Django 4.2 on 2024-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasic',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='회원', max_length=255, verbose_name='닉네임'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_id_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='user_nickname_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_index'),
        ),
        migrations.AlterModelTable(
            name='refreshtoken',
            table='refresh_token',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userbasic',
            table='user_basic',
        ),
        migrations.AlterModelTable(
            name='userextra',
            table='user_extra',
        ),
    ]
