# Generated by Django 4.2 on 2024-03-27 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_remove_user_user_nickname_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='계정생성 일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='계정활성 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='관리페이지 접근가능 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='모든 권한허용 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='마지막 로그인 일시'),
            preserve_default=False,
        ),
    ]
