# Generated by Django 4.2 on 2024-03-28 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_date_joined_user_is_activate_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='키')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='몸무게')),
                ('workout_time', models.IntegerField(blank=True, null=True, verbose_name='평균 운동량')),
                ('sleep_time', models.IntegerField(blank=True, null=True, verbose_name='평균 수면시간')),
                ('allergy_info', models.TextField(blank=True, null=True, verbose_name='알레르기 정보')),
                ('habit_info', models.TextField(blank=True, null=True, verbose_name='특이 식습관 정보')),
                ('preference_info', models.TextField(blank=True, null=True, verbose_name='선호 음식 정보')),
            ],
            options={
                'verbose_name': '회원 추가정보',
                'verbose_name_plural': '회원 추가정보',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('consent_terms', models.BooleanField(default=False, verbose_name='필수약관 동의 여부')),
                ('receive_marketing', models.BooleanField(default=False, verbose_name='마케팅정보 수신 여부')),
                ('gender', models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], max_length=50, null=True, verbose_name='성별')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='자기소개')),
                ('profile_image', models.TextField(blank=True, null=True, verbose_name='프로필 사진')),
            ],
            options={
                'verbose_name': '회원 기본정보',
                'verbose_name_plural': '회원 기본정보',
                'db_table': 'user_profile',
            },
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='계정활성 여부'),
        ),
        migrations.DeleteModel(
            name='UserBasic',
        ),
        migrations.DeleteModel(
            name='UserExtra',
        ),
    ]
