# Generated by Django 4.2 on 2024-03-28 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_userprofile_remove_userextra_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='키')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='몸무게')),
                ('workout_time', models.IntegerField(blank=True, null=True, verbose_name='평균 운동량')),
                ('sleep_time', models.IntegerField(blank=True, null=True, verbose_name='평균 수면시간')),
                ('allergy_info', models.TextField(blank=True, null=True, verbose_name='알레르기 정보')),
                ('habit_info', models.TextField(blank=True, null=True, verbose_name='특이 식습관 정보')),
                ('preference_info', models.TextField(blank=True, null=True, verbose_name='선호 음식 정보')),
            ],
            options={
                'verbose_name': '회원 건강정보',
                'verbose_name_plural': '회원 건강정보',
                'db_table': 'user_health',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
