# Generated by Django 4.2 on 2024-04-02 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userhealth_rename_is_activate_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원 기본정보', 'verbose_name_plural': '회원 기본정보'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '회원 프로필정보', 'verbose_name_plural': '회원 프로필정보'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=255, unique=True, verbose_name='사용자명'),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
