# Generated by Django 4.2 on 2024-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('D', 'DiningCoach'), ('K', 'Kakao'), ('N', 'Naver'), ('G', 'Google'), ('A', 'Apple')], max_length=50, null=True, verbose_name='가입 플랫폼 종류'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True, verbose_name='성별'),
        ),
    ]
