# Generated by Django 4.2 on 2024-04-09 04:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_platform_type_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile_image_path, verbose_name='프로필 사진'),
        ),
    ]
