# Generated by Django 4.2 on 2024-03-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '알레르기 카테고리',
                'verbose_name_plural': '알레르기 카테고리',
            },
        ),
        migrations.CreateModel(
            name='HabitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='카테고리명')),
                ('habit_type', models.CharField(max_length=50, verbose_name='식습관 종류')),
            ],
            options={
                'verbose_name': '식습관 카테고리',
                'verbose_name_plural': '식습관 카테고리',
            },
        ),
        migrations.CreateModel(
            name='PreferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '선호음식 카테고리',
                'verbose_name_plural': '선호음식 카테고리',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='카테고리명')),
                ('depth', models.IntegerField(default=0, verbose_name='카테고리 계층')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.foodcategory', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '식품분류 카테고리',
                'verbose_name_plural': '식품분류 카테고리',
            },
        ),
    ]
