# Generated by Django 4.2 on 2024-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergycategory',
            table='allergy_category',
        ),
        migrations.AlterModelTable(
            name='foodcategory',
            table='food_category',
        ),
        migrations.AlterModelTable(
            name='habitcategory',
            table='habit_category',
        ),
        migrations.AlterModelTable(
            name='preferencecategory',
            table='preference_category',
        ),
    ]
