# Generated by Django 4.2 on 2024-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('date', models.DateField(verbose_name='식단일기 날짜')),
                ('meal_type', models.CharField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snack')], max_length=50, verbose_name='식사 종류')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('is_favourite', models.BooleanField(default=False, verbose_name='즐겨찾기')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='회원')),
            ],
            options={
                'verbose_name': '식사일기',
                'verbose_name_plural': '식사일기',
                'db_table': 'meal_diary',
            },
        ),
        migrations.CreateModel(
            name='MealNutrition',
            fields=[
                ('amount_per_serving', models.FloatField(blank=True, default=0.0, null=True, verbose_name='1회제공량(g)')),
                ('calorie', models.FloatField(blank=True, default=0.0, null=True, verbose_name='칼로리(kcal)')),
                ('carbohydrate', models.FloatField(blank=True, default=0.0, null=True, verbose_name='탄수화물(g)')),
                ('sugar', models.FloatField(blank=True, default=0.0, null=True, verbose_name='당류(g)')),
                ('protein', models.FloatField(blank=True, default=0.0, null=True, verbose_name='단백질(g)')),
                ('fat', models.FloatField(blank=True, default=0.0, null=True, verbose_name='지방(g)')),
                ('cholesterol', models.FloatField(blank=True, default=0.0, null=True, verbose_name='콜레스테롤(mg)')),
                ('sodium', models.FloatField(blank=True, default=0.0, null=True, verbose_name='나트륨(mg)')),
                ('saturated_fat', models.FloatField(blank=True, default=0.0, null=True, verbose_name='포화지방(g)')),
                ('trans_fat', models.FloatField(blank=True, default=0.0, null=True, verbose_name='트랜스지방(g)')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diary.mealdiary', verbose_name='식사일기')),
            ],
            options={
                'verbose_name': '식사 영양정보',
                'verbose_name_plural': '식사 영양정보',
                'db_table': 'meal_nutrition',
            },
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('image_url', models.TextField(verbose_name='이미지 주소')),
                ('device_info', models.TextField(blank=True, null=True, verbose_name='기기 정보')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.mealdiary', verbose_name='식사일기')),
            ],
            options={
                'verbose_name': '식사 사진',
                'verbose_name_plural': '식사 사진',
                'db_table': 'meal_image',
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_code', models.CharField(max_length=50, verbose_name='식품코드')),
                ('food_name', models.CharField(max_length=255, verbose_name='식품명')),
                ('food_type', models.CharField(choices=[(1, 'Processed Food'), (2, 'Fresh Food'), (3, 'Cooked Food')], max_length=50, verbose_name='식품 종류')),
                ('portion', models.FloatField(blank=True, default=1.0, null=True, verbose_name='비율')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.mealdiary', verbose_name='식사일기')),
            ],
            options={
                'verbose_name': '식사 음식',
                'verbose_name_plural': '식사 음식',
                'db_table': 'meal_food',
            },
        ),
    ]
