# Generated by Django 4.2 on 2024-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mealdiary',
            table='meal_diary',
        ),
        migrations.AlterModelTable(
            name='mealfood',
            table='meal_food',
        ),
        migrations.AlterModelTable(
            name='mealimage',
            table='meal_image',
        ),
        migrations.AlterModelTable(
            name='mealnutrition',
            table='meal_nutrition',
        ),
    ]
