# Generated by Django 4.2 on 2024-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdiary',
            name='meal_type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], max_length=50, verbose_name='식사 종류'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='food_type',
            field=models.CharField(choices=[('P', 'Processed Food'), ('F', 'Fresh Food'), ('C', 'Cooked Food')], max_length=50, verbose_name='식품 종류'),
        ),
    ]
