# Generated by Django 4.2 on 2024-04-09 04:39

import diary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_alter_mealdiary_meal_type_alter_mealfood_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_food', to='diary.mealdiary', verbose_name='식사일기'),
        ),
        migrations.AlterField(
            model_name='mealimage',
            name='image_url',
            field=models.ImageField(upload_to=diary.models.meal_image_path, verbose_name='이미지 주소'),
        ),
        migrations.AlterField(
            model_name='mealimage',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_image', to='diary.mealdiary', verbose_name='식사일기'),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='meal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meal_nutrition', serialize=False, to='diary.mealdiary', verbose_name='식사일기'),
        ),
    ]
